[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
calling_program = "J2vJYgLFwppyahb2gMrJWJ7Uyn4sq1mCU8q6oJPWP3S7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
